# Use bibtex if a .bib file exists
$bibtex_use = 1.5;

# Generate pdf using lualatex
$pdf_mode = 4;

# Use qpdfview as pdf viewer
$pdf_previewer = 'start qpdfview --unique %S';
$always_view_file_via_temporary = 1;

# Remove more files during cleanup
$cleanup_includes_cusdep_generated = 1;
$cleanup_includes_generated = 1;
$clean_ext = 'pdfsync synctex.gz';
