#
# aerc account config with credential placeholders (check ~/.local/bin/aerc)
#

define(`FOLDERMAP', `/tmp/aerc-foldermap')
define(`write', `syscmd(`printf "%s" "$2" > '$1)')

cache-headers     = true
use-envelope-from = true
check-mail        = 5m
default           = INBOX
folders-sort      = INBOX
copy-to           = Sent
folder-map        = FOLDERMAP

write(FOLDERMAP,
Trash   = Deleted Items
Sent    = Sent Items
Junk    = Junk Email
Archive = Notes
)

[Posteo]
# -----------------------------------------------------------------------------
source        = imaps://$POSTEO_MAIL:$POSTEO_PASS@posteo.de:993
outgoing      = smtps://$POSTEO_MAIL:$POSTEO_PASS@posteo.de:465
from          = Jonas Belouadi <$POSTEO_MAIL>
aliases       = $POSTEO_USER+*@posteo.net,potamides*@posteo.net

[UNIT]
# -----------------------------------------------------------------------------
source          = imaps://$UNIT_USER:$UNIT_PASS@exchange.uni-mannheim.de:993
outgoing        = smtp+login://$UNIT_USER:$UNIT_PASS@exchange.uni-mannheim.de:587
from            = Jonas Belouadi <$UNIT_MAIL>
folders-exclude = ~Calendar\.?.*,Contacts,Journal,Outbox,Tasks
signature-cmd   = format(`printf "%s\n%s\n%s\n%s\n"',
  `Jonas Belouadi',
  `PhD Candidate | University of Mannheim',
  `Natural Language Learning & Generation Lab',
  `https://belouadi.com')

# vim: ft=dosini
