#
# aerc account config with credential placeholders (check ~/.local/bin/aerc)
#

define(`FOLDERMAP', `/tmp/aerc-foldermap')
define(`write', `syscmd(`printf "%s" "$2" > '$1)')

cache-headers     = true
use-envelope-from = true
check-mail        = 5m
default           = Inbox
folders-sort      = Inbox
copy-to           = Sent
folder-map        = FOLDERMAP

write(FOLDERMAP,
Inbox   = INBOX*
Trash   = Deleted Items
Sent    = Sent Items
Junk    = Junk Email
Archive = Notes
)

[Posteo]
# -----------------------------------------------------------------------------
source        = imaps://$POSTEO_MAIL:$POSTEO_PASS@posteo.de:993
outgoing      = smtps://$POSTEO_MAIL:$POSTEO_PASS@posteo.de:465
from          = My  Name <$POSTEO_MAIL>
aliases       = $POSTEO_USER+*@posteo.net,potamides*@posteo.net
# signature-cmd   = format(`printf "%s\n%s\n%s\n%s\n"',
#   `Jonas Belouadi',
#   `Senior AI Research Scientist',
#   `Autodesk Research | Autodesk AI Lab',
#   `https://belouadi.com')

[Cock.li]
# -----------------------------------------------------------------------------
source        = imaps://$COCKLI_MAIL:$COCKLI_PASS@mail.cock.li:993
outgoing      = smtps://$COCKLI_MAIL:$COCKLI_PASS@mail.cock.li:465
from          = Jonas Belouadi <$COCKLI_MAIL>

# vim: ft=dosini
