#
# aerc account config with credential placeholders (check ~/.local/bin/aerc)
#

cache-headers     = true
use-envelope-from = true

[Posteo]
# -----------------------------------------------------------------------------
source        = imaps://$POSTEO_MAIL:$POSTEO_PASS@posteo.de:993
outgoing      = smtps://$POSTEO_MAIL:$POSTEO_PASS@posteo.de:465
default       = INBOX
from          = Jonas Belouadi <$POSTEO_MAIL>
aliases       = $POSTEO_USER+*@posteo.net,potamides*@posteo.net
copy-to       = Sent
folders-sort  = INBOX

[UNIT]
# -----------------------------------------------------------------------------
source          = imaps://$UNIT_USER:$UNIT_PASS@exchange.uni-mannheim.de:993
outgoing        = smtp+login://$UNIT_USER:$UNIT_PASS@exchange.uni-mannheim.de:587
default         = INBOX
from            = Jonas Belouadi <$UNIT_MAIL>
copy-to         = Sent Items
archive         = Notes
folders-exclude = ~Calendar\.?.*,Contacts,Journal,Outbox,Tasks
folders-sort    = INBOX
signature-cmd   = format(`printf "%s\n%s\n%s\n%s\n"',
  `Jonas Belouadi',
  `PhD Candidate | University of Mannheim',
  `Natural Language Learning & Generation Lab',
  `https://belouadi.com')

# vim: ft=dosini
