#
# aerc main configuration with m4 macros (check ~/.local/bin/aerc)
#

[general]
# -----------------------------------------------------------------------------

# display hyperlinks
enable-osc8=true
# default shell command to use for :menu
default-menu-cmd=fzf --multi
term=xterm-256color

[ui]
# -----------------------------------------------------------------------------

# do not differentiate between old ("O") and new ("N") messages
column-flags={{.Flags | join "" | replace "O" "N"}}
styleset-name=ifelse($TERM,linux,default,gruvbox)
# display sender in "sent" folders
column-name={{if match .Folder "^(Gesendet|Sent)"}}{{index (.To | names) 0}}{{else}}{{index (.From | names) 0}}{{end}}
dirlist-right={{if .Unread}}{{humanReadable .Unread}}/{{end}}{{humanReadable .Exists}}
dirlist-tree=true
sidebar-width=30
reverse-thread-order=true
threading-enabled=true
mouse-enabled=true
fuzzy-complete=true

[statusline]
# -----------------------------------------------------------------------------

# use box-drawing character instead of pipe
column-right={{.TrayInfo}} │ {{cwd}}
separator=" │ "

[viewer]
# -----------------------------------------------------------------------------
max-mime-height = 10

[compose]
# -----------------------------------------------------------------------------

# own addressbook implementation, see filters/addressbook.py
address-book-cmd=$HOME/.config/aerc/filters/addressbook.py --match %s
file-picker-cmd=fzf --multi --query=%s
reply-to-self=false
empty-subject-warning=true
no-attachment-warning=^[^>]*attach(ed|ment)

[multipart-converters]
# -----------------------------------------------------------------------------
text/html=pandoc -f markdown -t html --standalone

[filters]
# -----------------------------------------------------------------------------
to,~.* daily title/abstract distribution <rabble@arXiv.org>=arxiv.py | colorize

text/plain=addressbook.py | colorize
text/html=addressbook.py | pandoc -f html -t plain --reference-links | colorize
message/delivery-status=colorize
message/rfc822=colorize
text/calendar=calendar | colorize
application/ics=show-ics-details.py | colorize
application/pdf=pdftotext - -l 10 -nopgbrk -q  - | fmt -w 100

# only used when [viewer].show-headers=true
.headers=colorize

[openers]
# -----------------------------------------------------------------------------

# delegate opening logic to rifle and xdg-open
x-scheme-handler/*=xdg-open
*/*=rifle -f f

[hooks]
# -----------------------------------------------------------------------------
mail-received=notify-send "[$AERC_ACCOUNT/$AERC_FOLDER] New mail from $AERC_FROM_NAME" "$AERC_SUBJECT"

# vim: ft=dosini
